import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { AuthProvider } from "./components/provider/Provider";
import ClientReduxProvider from "./components/clientReduxProvider/ClientReduxProvider";
import store from "./store/store";

// import Footer from "./components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
      <AuthProvider>
      <ClientReduxProvider store={store}>
          {children}
        </ClientReduxProvider>
        </AuthProvider>
       
        {/* <Footer /> */}
        </body>
    </html>
  );
}
